### ISSUE TITLE
✨ [Feature] 회원 가입 로직에 이메일 본인 인증 과정 추가

### ISSUE THREAD

**Issue by Austin-Choi** [5-ReBook/ReBook_BE#19]
### Description

![회원 가입 흐름도](https://github.com/user-attachments/assets/9f358f5e-a9c9-4e0b-ae90-1d3e4bdc84dd)
이해를 위한 흐름도이므로 실제 구현과는 조금 다를 수 있습니다.
기존 회원 가입 로직에서 이메일 본인 인증 과정을 추가로 구현합니다. 

- /auth/members/signup/mail : username을 받고 3분간 유효한 6자리 인증번호를 redis에 저장하고 사용자에게 메일을 보냅니다.
- /auth/members/signup/verify : 인증번호, username, password 를 입력으로 받아 redis에서 인증번호를 불러오고 일치하면 저장합니다.

### Todo

- [x] /members/signup/mail구현하기
- [x] /members/signup/verify 구현하기
- [x] rebook-common 에서 ErrorCode에 인증 번호 관련 에러 추가하기
- [x] /members/university, /members/majors DB 직접 접근하는 메서드에 적합한 어노테이션 붙이기
- [ ] gradle 문제 해결하기..
