### ISSUE TITLE
🔨 [Refactoring] 멀티모듈, 유틸리티 모듈 분리

### ISSUE THREAD

**Issue by greatSweetMango** [5-ReBook/ReBook_BE#20]
### Description

멀티모듈 빌드를 위해서 유틸리티 모듈을 분리합니다.

### Todo

- [x] 내부 구조에서 의미상 utils 분류하기
- [x] 최상위 루트에서 rebook-utils 폴더 생성하기
- [x] build.gradle 수정을 통해 각각의 모듈로 분리하기
- [x] 잘 빌드 되는지 테스트하기

**Comment by greatSweetMango** [comment]
모듈 이름을 utils보다는 common으로 가져가야 될까 싶긴 합니다.
