### ISSUE TITLE
🔨 [Refactoring] Product 동작하지 않는 기능 수정

### ISSUE THREAD

**Issue by namkikim0718** [5-ReBook/ReBook_BE#31]
### Description

- 소스코드를 수정하면서 잘 동작하지 않는 기능들이 생겼습니다.

### Todo

- [x] 컨트롤러 인식하지 않는 문제 해결
- [x] member 모듈과의 분리
- [x] product 엔티티의 필드 mvp에 맞게 수정
- [x] s3관련 로직 common 모듈로 빼기
