### ISSUE TITLE
✨ [Feature] S3 신규 설정에 맞춰 수정, 삭제 기능 추가

### ISSUE THREAD

**Issue by Austin-Choi** [5-ReBook/ReBook_BE#44]
### Description

rb-dev-s3-images 버킷으로 yml 설정을 수정합니다.
신규 S3 버킷명과 폴더 구조를 고려해서 기존 기능을 수정합니다.
common 모듈의 S3Config에 삭제 기능을 구현합니다.
폴더명을 타입으로 관리합니다.

### Todo

- [x] yml 설정 수정
- [x] 폴더명 타입으로 관리하기
- [x] 폴더명 고려해서 기존 기능 수정하기
- [x] 삭제 기능 추가하기
